[[countdown]]
title = "MBP update"
datetime = "2025-07-12 12:00:00"

[[countdown]]
title = "wedding annual"
datetime = "2024-09-26 00:00:00"

[[countdown]]
title = "son 2st birthday"
datetime = "2024-12-02 16:00:00"

[[countdown]]
title = "off working hour"
datetime = "2024-08-29 18:00:00"

[[countdown]]
title = "Olympic summary"
datetime = "2024-08-29 14:30:00"

[[countdown]]
title = "Lord Of Ring S2"
datetime = "2024-08-30 10:30:00"

[[countdown]]
title = "15 years working"
datetime = "2028-07-07 10:30:00"

[[countdown]]
title = "sleep time"
datetime = "2024-08-29 23:30:00"
