[[countdown]]
title = "MBP update"
datetime = "2025-07-12 12:00:00"

[[countdown]]
title = "wedding annual"
datetime = "2024-09-26 00:00:00"

[[countdown]]
title = "son 2st birthday"
datetime = "2024-12-02 16:00:00"

[[countdown]]
title = "off working hour"
datetime = "2024-08-23 18:00:00"

[[countdown]]
title = "sleep time"
datetime = "2024-08-25 00:00:00"
